### ISSUE TITLE
Contributing issues with coffeescript

### ISSUE THREAD

**Issue by johnhornsby** [logankoester/grunt-phonegap#131]
I have needed to make an update to ensure the latest iOS icons and splash screens are dealt with in the build task. I have never contributed and so am unsure if I should be compiling my coffeescript without the  `// Generated by CoffeeScript 1.7.1` at the top of each js file. If I need to remove what is the typical work flow for this?

**Comment by gabrielpoca** [comment]
Hey @johnhornsby , I'm sorry for the delay. Those comments don't show up to me, maybe there is an option remove it. But because those files are generated it will not be an issue as long as your coffee is ok. Open the pull request and we can discuss it further there. I hope my delay doesn't discourage you from contributing.
